### ISSUE TITLE
Email to create cards

### ISSUE THREAD

**Issue by GliderPro** [kiswa/TaskBoard#122]
Trello has a feature which creates an email address for a column and any email received there makes a new card. This is great for when you are mobile and need to save an idea to get it out of your head. I'm hosting TaskBoard on Dreamhost and it looks like it is possible to execute a PHP script when an email message is received. http://wiki.dreamhost.com/Email_to_Script

I'll try to prototype this with a simple script. If it works it could be a nice addition to TaskBoard.

EDIT: I tried this out and it works. I had to setup forwarding to a shell account following these instructions. http://wiki.dreamhost.com/Shell-linked_E-mail#Forward_to_a_shell_account

From there I setup a .forward.postfix with the following contents `"|/home/shellacct/filter.php"`

The filter.php script simply saved the contexts to a log file.

> # !/usr/local/php56/bin/php
> 
> <?php
> $data=print_r($_SERVER,1);
> $fd = fopen("php://stdin", "r");
> $email = "";
> while (!feof($fd)) {
>   $email .= fread($fd, 1024);
>   }
>   fclose($fd);
>   //Now your mail is in $email and you can save it
>   //to a database or POST it to somewhere.
> file_put_contents('/home/shellacct/filter.log',$data.$email);
> ?>

EDIT 2: You can use email extensions to create unique column references. For example `user+board1_inbox@domain.com` and `user+board2_backlog@domain.com` will get forwarded to `shellactt@webserver` but the "To:" header in the message will retain the original address. With this approach you could configure any number of email aliases for creating cards on specific boards.

**Comment by kiswa** [comment]
Interesting. I actually have plans to develop a mobile app for TaskBoard (though it's down the road a ways). This could certainly be useful to some though.

**Comment by torwag** [comment]
I would like to second this idea. 
Many programs try to create an own eco-system. However, even they are good, they often fail because people do not use them.
The reason is peoples inertia.
1. Log-in to the website
2. Add the new task
3. Assign co-workers
4. Keep checking which tasks belong to you / are assigned to you
5. Check how tasks proceed
6. Log out

In theory this works out. However, what it is most likely is the fact that many many people and co-workers simply use emails and those are hard to convince to use just another system in addition.
1. Write an email to a colleague to take care of a task
2. Receive emails with tasks
3. Writing emails forth and back asking for a task status  resp. giving feedback for a task status.

Whereas point 1 and 2 are easy and most people prefer to do it that way, point 3 is boring and time consuming.  
If Taskboard would allow

1. Sending emails to TaskBoard and coworkers to create a task
2. TaskBoard send emails whenever a user-specified event happens

That would allow to send emails to coworkers as usual, however simply adding and email for  TaskBoard to add the task to a defined board and slot. 
Thus, people can easily log-in to get an graphical up-to-date overview of all tasks and modify them.
If they modify a task, e.g. adding a new responsible person or moving it to another slot, TaskBoard should send emails to all assigned people. Thus they get a feedback even without login Taskboard.

This method would help to integrate Taskboard to all kind of workflows. People could use it with all kind of software on all kind of platforms (mobile, webmask, PC, MAC, etc.). After all there is an email client for almost everything. Thus, Taskboard would be integrated with many workflows and this all without a single line of code support for clients from TaskBoard itself.
