### ISSUE TITLE
Allow multiple tasks per row in column

### ISSUE THREAD

**Issue by Kernle32DLL** [kiswa/TaskBoard#129]
It would be cool it columns could be configured to have multiple tasks per row, rather than just one long list.

Here an illustration how this could look:
![taskboard_multicol2](https://cloud.githubusercontent.com/assets/1338408/6111524/bf9ab66a-b089-11e4-92fb-62f8da55250c.png)

In its most simple form, a simple numeric board option on "how many tasks per column row" could be implemented (default 1). Next step would be to make this configurable per column.

The most awesome - and also probably most work involved - option would be an auto-ordering/sizing depending on length of title and description.

**Comment by kiswa** [comment]
This is covered by #120 I believe (if not, please let me know). Thanks for the visual, that's handy!

**Comment by Kernle32DLL** [comment]
Well that depends on your implementation ;-) But yeah, I saw #120. I just overlooked the comment the "more tasks per row" comment.

Looking at the visual, you might want to go for something like Masonry (look it up, its an jQuery plugin of sorts), because as the visual shows: The fun begins with tasks having different heights (and making them the same height per-"row" would be waste of space again).

This might conflict with #77 tho, as the visual not clearly expresses an order (look at the 3 yellow boxes vs the 2 green boxes at the top. In which order are they?)

**Comment by kiswa** [comment]
Yeah, there would have to be a choice made on what sorting means when there are two columns of items. Most likely, it would be sorted left-to-right then top-to-bottom, but I'd be open to input on that.

I'm thinking it would be best to keep it simple and have something for each column like "Display Tasks Side-By-Side" to allow turning this display on and off. Then it would just sort by whatever order is setup and flow the tasks as they fit (rather than having strict rows in a column).
