### ISSUE TITLE
Quick Add Item

### ISSUE THREAD

**Issue by sebelk** [kiswa/TaskBoard#135]
Hi, I think It would be nice if taskboard has the capability of quick add entry as in Trello.
And then if you want to add details to the task, only you have to edit it.

Thanks in advance!

**Comment by kiswa** [comment]
Are we talking about a title-only kind of thing here?

**Comment by kiswa** [comment]
I'm going to assume this means a 'title only' item add option, because that sounds like it could be useful.

**Comment by hi2u** [comment]
This is probably obvious, and you're doing it this way anyway...

But there's already vertical space being used next to the [+] button, so all you need to do is put the text input field to the left of that, and it won't take up any extra space on the screen (as opposed to sticking them on the top)...

![taskboard-quick-add-title](https://cloud.githubusercontent.com/assets/9689599/6955929/ba8292e8-d928-11e4-83ec-af7a812237b6.png)

Although some people might prefer them all lined up along the top?  But doing like about would save some space, and doesn't require a popup/modal dialog.

Thanks for your work on this great program, @kiswa - I'm really loving it.  I much prefer the interface compared to Trello.

**Comment by kiswa** [comment]
Actually, I hadn't thought of that. I like it, thanks!

**Comment by greatawesome** [comment]
I am having trouble with this feature. When I create an item with the quick add function, I am not able to edit it. I try right clicking on it and selecting Edit Item, and nothing happens. If I click View Item, the item dialog comes up, but hitting the Edit button in that dialog just causes it to close. 

If I do a browser refresh of the board, editing works fine.

UPDATE: It turns out that after doing a quick add, I am not able to edit ANY item on the current board, not just the one I added.
