### ISSUE TITLE
Feature Request : Swimlanes

### ISSUE THREAD

**Issue by GliderPro** [kiswa/TaskBoard#139]
Many people incorrectly refer to swimlanes as the columns of the board but they are actually horizontal rows that can group cards. They are an easy way to visualize multiple projects, users, or whatever else you want to group by. Would something like this be possible with your current architecture?

**Comment by kiswa** [comment]
With the current setup, no not really.

I don't know that TaskBoard should have swimlanes either, as it's meant to be a simplified kanban board. Multiple projects = multiple boards; users = filtering, etc. For now, I don't think swimlanes will be in TaskBoard.

**Comment by cheesebricks** [comment]
Hi Kiswa, 

Since Kanban is a flexible method it's not necessarily mean that Multiple projects = multiple boards; users = filtering.
Some time users use a board (usually when group of people work together on a project but each person had different responsibility) and horizontal lines help them to create a stream per person.

Eventually it just mean ability to add horizontal line (I.E ---------------------------------) that move up/down based on the location of the tasks. no more than that.

Hope you would reconsider this (I think it suppose to be quite easy to develop - but hey, it's easy to say from the outside).

Again - thanks for a great product.
