### ISSUE TITLE
We could not login to the TaskBoardhe

### ISSUE THREAD

**Issue by Means0305** [kiswa/TaskBoard#243]
We downloaded the current version's TaskBoard. And install it to Apach 2.4 + PHP 5.5 server.
We can open the login screen (http://localhost:8080/TaskBoard), but when we input the user id and password (admin/admin) and clicked the login button, we could not enter the TaskBoard like what demo showed to us.

**Comment by bf-ckiendl** [comment]
See #217 and potentially the comments of #200.

**Comment by 2b3pro** [comment]
I have the same problem. Cannot login for the first time using admin/admin. 

In my Safari console, it says "Failed to load resource: the server responded with a status of 404 (Not Found)" from /api/login.

**Comment by kiswa** [comment]
@Means0305 Can you give the error from dev tools?

@2b3pro That sounds like you did not make `api` writable.

**Comment by arborrow** [comment]
Just documenting that I was getting a 500 error on login. I was attempting to run on a shared host (HostMonster) and had to use php ./build/composer.phar install to pull things in. I suspected there may have been something with the php.ini that might be preventing things from running but was not seeing errors logged where I would normally expect them. 

The post appeared fine with json data:
password  "admin"
rememberme	false
username "admin"

; however, the response I am getting is:



<html><head><title>500 Server Error</title></head>
<body bgcolor=white>
<h1>500 Server Error</h1>

A misconfiguration on the server caused a hiccup.
Check the server logs, fix the problem, then try again.
<hr>

URL: http://taskboard.montserratretreat.com/api/login<br>


</body></html>

I attempted on another server and was able to discover in the /var/log/apache2/error.log lines like:

[Sun Dec 27 14:34:38.490544 2015] [core:alert] [pid 17378] [client 207.119.47.246:55201] /var/www/TaskBoard/api/.htaccess: Invalid command 'ExpiresActive', perhaps misspelled or defined by a module not included in the server configuration, referer: http://isi.montserratretreat.com/taskboard/

in the error log. 

So it appears that it was because mod_expires was not enabled on the shared host. Once I enabled mod_expires on my other server the login worked smoothly. Peace - Anthony

**Comment by kiswa** [comment]
Another option would be to edit the `.htaccess` to remove the caching settings if it's not possible to enable `mod_expires`.

**Comment by samjk1** [comment]
I had the same issue and solved it by configuring the mod_rewrite properly, adding:

<Directory "/var/www/html">
    AllowOverride All
</Directory>

To the end of the file "/etc/apache2/sites-available/000-default.conf".

**Comment by kiswa** [comment]
@Means0305 I'm closing this for now. If you're still having problems, just comment and we can re-open.

**Comment by arborrow** [comment]
Just following up that on my shared hosting account, the issue was not with mod_expires after all. Hostmonster does have that enabled by default for their shared hosting. Instead, it was a file permissions issue - I had gone ahead and set 775 on the api folder and apparently that was causing an issue - see https://my.hostmonster.com/cgi/help/594#permissions - for more information. I was confused as to why I was not seeing an error in the server logs but once I set the permissions to 755 I was able to login without issue. Peace - Anthony
