### ISSUE TITLE
When editing a board, columns always show in the order of creation - although they are already re-ordered

### ISSUE THREAD

**Issue by flowli** [kiswa/TaskBoard#265]
Is that a correct observation?

**Comment by kiswa** [comment]
Somehow I never saw this issue.

When editing a board, the columns should be displayed in the same order as on the board itself (except left-to-right becomes top-to-bottom).

**Comment by flowli** [comment]
Thanks for caring :-) Unfortunately I switched to Wekan and cannot give further details anymore. But I'm sure I made this observation.

**Comment by olaulau** [comment]
we also have this bug :
- in setting screen, columns are in the right order.
- after clicking the edit button, they appear in order of creation
so I think the fix is very quick, please :-)

**Comment by olaulau** [comment]
I also noticed that having more that 10 columns is bugged :
displayed order is 0, 1, 10, 11, 12, ..., 2, 3, 4, ...
problem of string order instead of number order !

**Comment by Algorithmus** [comment]
I only looked at this in the rewrite, but apparently, the columns are only sorted in effectively one place in the `board.component.ts` constructor. The `addTask`, `updateTask` and `removeTask` functions in the column component call the `updateActiveBoard` function, but that function never does any column sorting, so it displays in the order the api gives it in, which is the order the columns were created in.

This also happens when you try to move the task to a different column from the context menu.
