### ISSUE TITLE
autoactions request interval

### ISSUE THREAD

**Issue by FiSHYsolutions** [kiswa/TaskBoard#276]
TaskBoard causes a lot of 'autoaction'-requests. It slows down the overall-performance and increases needless pagetraffic. I'm the only user of my Board (fresh v0.3.1) and defined four autoaction-rules.

The webserver gets a request every 2 seconds and I can't understand the reason, because i didn't changed any content in my board and autoactions should only be triggered by human interaction.

```
bash$ pwd
/var/log/apache2
bash$ grep '21/Apr/2016.*autoactions ' access.log | wc -l
1042
bash$ grep '21/Apr/2016.*autoactions ' access.log | head -1 | cut -d' ' -f4-5
[21/Apr/2016:12:20:41 +0200]
bash$ grep '21/Apr/2016.*autoactions ' access.log | tail -1 | cut -d' ' -f4-5
[21/Apr/2016:12:56:05 +0200]
```

I reduced the impact by increasing the interval, but IMHO it's no neat solution:

```
bash$ diff /var/www/TaskBoard/js/controllers/settingsAutoActions.js*
201c201
<     $interval($scope.loadActions, 10000);

---
>     $interval($scope.loadActions, 2000);
```

**Comment by kiswa** [comment]
It's not a good solution. And unfortunately, there are several poor design choices in the code that are too cumbersome to correct with the current architecture.

That's why I'm currently working on a complete re-write with maintainability in mind. When I originally wrote TaskBoard it was meant as a way to learn AngularJS (and make something I'd use). Now that it's being used by others (a fair few), it needs to be more maintainable. Plus, this time I know the requirements much better.

**Comment by rbakker** [comment]
Hi Matthew,
I just started to use TaskBoard and think it is a great tool to get myself organized. Nothing escapes my attention anymore, and it works offline! I am posting in this topic because this is the major drawback of the software, the autoactions cause so much processing that my laptop battery drains significantly faster. Great to hear that you are getting rid of them altogether, can't wait!
RB
