### ISSUE TITLE
Request for User Feedback - UPDATED 6/9/2016

### ISSUE THREAD

**Issue by kiswa** [kiswa/TaskBoard#288]
I am currently working on a complete re-write of TaskBoard which will solve many issues with maintainability and ease-of-development (as well as proper drop-in installation).

I have created a mock-up of the new Settings page and would like your feedback on it, as well as ideas about making TaskBoard as useful as possible while keeping it minimalist.

![Settings Page Mock-Up](https://i.imgur.com/lcnb9i0.png)

Ignore the dark patch at the bottom left, it's an artifact from the screen capture, not part of the mock-up.
## Update 6/8/2016

Here's the latest mock-up (I got tired of API work again). This is what I'm picturing for the Dashboard page. The last section would only show up for admin or board admin users.
### Update 6/9/2016

I realized I should have a calendar on the Dashboard as well! (See #79)

![Dashboard Page Mock-Up](https://i.imgur.com/EsuPsOx.png)

**Comment by Pocc** [comment]
Is there a way to not make the page "bounce" when you move an item from column A to column B? It's a cool animation, but I think there should be some way to disable it.

**Comment by Pocc** [comment]
Also, there should be a list of keyboard shortcuts when you hit '?' or 'ctrl+/' like in Gmail, Asana, or many other websites.

**Comment by kiswa** [comment]
The "bounce" is probably due to the way it currently refreshes after a change. This should go away in the new implementation.

Keyboard shortcuts are an interesting idea. Can you give me a few examples of some that would be useful?

**Comment by Pocc** [comment]
When you're hovering over a card, you could do the following: Press

- t to edit the title
- e to edit the descriptoin
- A to add an attachment

When nothing is selected, Press

- a to add a card and immediately go into edit mode
- b to go to board select
- f to jump to filter
- h to hide filtered cards

This are example suggestions. I would recommend going to different websites and press "shift OR ctrl+/" and see what happens. I screenshotted [Trello](http://tinypic.com/r/27zgill/9) and [Gmail](http://tinypic.com/r/2d7cz11/9), so you could get an idea of what I'm talking about.

**Comment by kiswa** [comment]
Nice, thank you.

**Comment by fernandodiacenco** [comment]
Hello,

I was looking for a Kanban styled ticketing system for our company and Taskboard appeared as one of the more interesting options

BUT as it is it cannot replace our existing ticketing system without more features,  so I will point the features needed as a suggestion for future development, many may not be feasible to implement (and some may already exist) but at the very least this serves as food for thought

1) Multiple boards with visibility options so I can set whenever one department can or cannot see other department board

2) Email to card/task: This would work like this: a master email is configured like contact@company and and alias to this email is created like contact.sales@company, taskboard is them configured as to when receiving email from contact.sales it opens a new task/card on the board "Sales Dept"

When a new task/card is created the person who sent the email receives a email back as notification "a ticket has been created with the number <#task_number>" and when the card is moved to column done the user receives another email "your ticket has been closed blahblahblah"

This way with one email the company can have an indefinite number of aliases and boards and some end user interaction

3) Scheduled or recurring cards/tasks: Possibility to schedule the opening of a card/task and daily/weekly/monthly scheduling for tasks that must be done everyday but can't be quite automated yet

4) Schedule task/card to be created when another is closed (moved to column 'done' or something), that way the manager of the team can set tasks days in advance  and the team keeps receiving tasks in its own time

5) LDAP integration: This is not critical, would just make things easier, if that is made someday PLEEEEASE add a "test ldap connection" button  on the same page of ldap config, because the main way to test ldap integration is logging out of the current internal user and logging in with the ldap user and that is annoying as hell

6) A place to upload the company logo

In any case thanks for the attention and I sincerely hope this feedback might be useful somehow / someday.

**Comment by kiswa** [comment]
@fernandodiacenco Thanks for all the feedback!

LDAP is on the roadmap, so that will happen eventually. The other recommendations definitely give me some ideas. There is certainly a lot that could be done with the use of email and TaskBoard.

**Comment by fernandodiacenco** [comment]
Thanks for answering Matthew!

I've made some interface mockups to serve as reference when searching for a Kanban board to replace our OTRS

Perhaps they might be useful to you somehow.
________

![01](https://cloud.githubusercontent.com/assets/2643364/16688577/09cdcf32-44f5-11e6-9fdc-2d73f208bc82.png)
![02](https://cloud.githubusercontent.com/assets/2643364/16688578/09d2d748-44f5-11e6-8508-6ff918d67609.png)
![03](https://cloud.githubusercontent.com/assets/2643364/16688579/09d39bf6-44f5-11e6-8cce-70b2c3b91886.png)

**Comment by srdco** [comment]
2 enhancements would make TaskBoard even better for project management / solo development / product development:
1) time tracker (that could be used per task) - that way we don't have to duplicate tasks in a separate time tracker software
2) modify boards on the front-end (add categories and especially sections) - much faster than having to go to a large settings page.

**Comment by kiswa** [comment]
For the time tracker... are you thinking of something like a `start tracking time` button that you click and it changes to `stop tracking time` then shows a `time spent` value on the task? I can see that being useful and it should be fairly straightforward to add.

I'm not sure about having category/section changes made from the board itself. It feels to me like those things should be kept separate. I'd be glad to hear more opinions on this!

**Comment by srdco** [comment]
Yes to the time tracker - pretty much exactly what I'm thinking, with total times per task and per project ... if not too hard.

The sections on the board could still be editable on the backend - and probably on the front-end only for certain permissions? However, too many times, I want to add tasks and need to add a new category or a new section (categories especially, sections aren't as big a deal) - like a new phase to the project, and it interrupts the workflow to have to go edit it in the settings. Part of the beauty of your front-end is the ability to quickly edit the task breakdown without spending inordinate amounts of time planning out every little detail of the project before planning it.

**Comment by srdco** [comment]
Also, I second the scheduling requests. Not as big as the time tracker for our uses ... but certainly would be great features!

**Comment by kiswa** [comment]
Categories I can see the need for more frequent changes. I'll try to figure out a good way to change them from a board.

The scheduling of tasks is requested enough that it's on my list for the re-write (though the new task after one 'closes' may be a later enhancement).

Some of the things suggested so far are, at best, going to happen after the re-write is released anyway.

**Comment by srdco** [comment]
Wait? You mean open source developers don't have unlimited time?? ;-) Thanks for the whole project!

Like I said -- timing is big.

Also, a way to view ALL current tasks would be great, but wouldn't make sense until there's scheduling (due on X, assigned to X) then query all those and display on a calendar...

**Comment by kiswa** [comment]
> Also, a way to view ALL current tasks would be great, but wouldn't make sense until there's scheduling (due on X, assigned to X) then query all those and display on a calendar...

That's in the new Dashboard page!

**Comment by srdco** [comment]
Awesome!

**Comment by Theooo** [comment]
I really like the task checklist feature from Restyaboard.

Basically, for each item you can add a customized checklist with names for each checklist item.
Afterwards, you can select those checklist items and automatically get a progress bar shown with an overall percentage check in the checklist. 

Sometimes, I create tasks which take quite a while to finish. With the checklists, I still keep an overview of the progress even though the item isn't split in multiple items and is not disturbing me from my other work too much. :)

**Comment by kiswa** [comment]
I was planning to add checklists, but I like the idea of a progress bar as well. Thanks for the input!

**Comment by tkjacobsen** [comment]
A couple of ideas:

* Allow for assigning tasks to people not in the system. Will be useful when working in teams where only some (e.g. a core team) are using the system to keep track of delegated tasks

* Ability to attach and filter on arbitrary tags (e.g. items to bring for specific meeting, discuss with someone, urgency, criticality - by making it arbitrary user can do many individual customizations). Should be possible to add multiple tags to one item.

* Inline editing instead of opening a pop-up

**Comment by kiswa** [comment]
I'm not sure the first one is worth the dev effort - just add them as users.

Tags have been mentioned several times now. I will implement them basically as you have written.

I can see the benefits of inline editing for portions of a task, and will think about ways to make that possible. However, the popup will still be the main detail view of a task that lets you see everything (attachments, comments, etc.).

**Comment by atsepkov** [comment]
+1 on the checklists, checklists + recurring tasks would actually allow me to replace HabitRPG with this as my main daily planner:
![screen shot 2016-11-30 at 3 20 21 pm](https://cloud.githubusercontent.com/assets/2549997/20769622/c4fb950e-b710-11e6-9beb-e4bdc632220e.png)

By the way, wouldn't checklists already be supported in existing version via github-flavored markdown or is there something else that would prevent them from working as expected?

### source

    - [ ] foo
    - [ ] bar
    - [x] baz

### result
- [ ] foo
- [ ] bar
- [x] baz

**Comment by sergeevabc** [comment]
Is project dead?

**Comment by kiswa** [comment]
@sergeevabc Not at all. The rewrite is coming along nicely.

**Comment by sergeevabc** [comment]
How to track the progress then? E.g., progress of [Kanboard][1], alternative to Taskboard, is available monthly.

[1]: 
https://github.com/kanboard/kanboard/blob/master/ChangeLog

**Comment by kiswa** [comment]
I setup a project that shows the current state of my work on the re-write: https://github.com/kiswa/TaskBoard/projects/1?fullscreen=true

**Comment by kiswa** [comment]
Also, I post monthly on [my blog](https://matthewross.me/blog) (almost always about TaskBoard).
