### ISSUE TITLE
Reflect automatic actions within the edit dialog

### ISSUE THREAD

**Issue by SebastianZ** [kiswa/TaskBoard#299]
If there is an automatic action on a change, the action should have a direct effect within the edit dialog.

- If a color is set, set it within the dialog and deactivate the color selection field.
- If the item assignee is changed, change them within the dialog. (Better would be to disallow setting the user at all, but that would rather require a new UI for deactivating users.)
- If the due date is cleared, deactivate the date selection field and clear it within the dialog.

In all cases the user should somehow be informed immediately about the actions, e.g. via a popup message like the one shown when you save the edits (but with different background color).
That message should say something like:

"Automatically set _item_'s color to _\#bee7f4_ because it was assigned to user _Demo_"

Multiple actions happening on a trigger should either cause multiple messages or both actions should be included in one message.

Sebastian

**Comment by kiswa** [comment]
Agree on the messages, not the rest.

Automatic actions are meant to be time savers that do a few minor things for you. They are not meant to be a **this is the way it must be** thing for tasks. TaskBoard does not restrict editing of anything for users with access to a board.

**Comment by SebastianZ** [comment]
It's bad UX if a user can still set the related options and they get changed automatically afterwards.
A program should always be predictable.

But I agree that it may go beyond the idea of automatic actions.

Sebastian

**Comment by kiswa** [comment]
The related options should only change when a trigger is activated (*e.g.* move to column).

If the automatic actions are resetting things after an edit, then yeah, that's a bug.

**Comment by SebastianZ** [comment]
> If the automatic actions are resetting things after an edit, then yeah, that's a bug. Is that what's happening (and if so, can you give me a repeatable example)?

Imagine you have an automatic action that sets the color when an item is assigned to a specific user. When you then create an item, select that user and select a different color for it and then click the *+ Add Item* button, the color is changed due to the automatic action.
This may be unexpected by the user, because they explicitly set some color.

Sebastian

**Comment by kiswa** [comment]
Ah, I get what you're saying.

I just don't think the development effort required to check automatic actions and enable/disable controls based upon user interactions is worth it.

For example, in your scenario when a task is being created it would have to watch for changes to the assigned user. Then, if the selected user has one or more automatic actions tied to them, figure out what controls on the form must be set to certain values, set them, then disable them. This has the potential to get very complex very quickly.

It seems to me to be minimal cognitive load for a user to go, 'Why did that change colors?" then remember that they have automatic actions and assume it was because of one of them.

**Comment by SebastianZ** [comment]
Yes, it would require some effort and can get complex with more actions.

Anyway, having proper messages informing people about what's happening would already be a big win.

Sebastian
