### ISSUE TITLE
Row refreshes after 8-10 seconds

### ISSUE THREAD

**Issue by therealmaxmoon** [kiswa/TaskBoard#331]
If a row has a lot of tasks and you scroll down to read them, something refreshes the row every 8-10 seconds and you have to scroll down again. It's pretty annoying if you want to read important stuff. 

Is there a way to deactivate this refresh?

**Comment by kiswa** [comment]
I suppose you could go into the front end code and make some changes to disable this. Specifically [comment out this line](https://github.com/kiswa/TaskBoard/blob/master/js/controllers/boards.js#L143) and the one below it.

That said, it is going to be fixed in the re-write (which I'm still working on).

**Comment by therealmaxmoon** [comment]
I've commented those 2 lines out. But it still refreshes a row after 10 seconds. I've restart the server and emptied the cache, but the refreshes still exist.

Any other way to avoid refreshes?

**Comment by therealmaxmoon** [comment]
Is there another way to stop those refreshes?
