### ISSUE TITLE
Change date format (for due date)

### ISSUE THREAD

**Issue by Schokobecher** [kiswa/TaskBoard#335]
Is there a simple way to change the date formart of the due date (or in general).
I would prefer 'dd/mm/yyyy',

 I checked the jQuery docs for the datepicker and the Angular JS docs for the format but I never really worked with JS so I have no clue where to start.

**Comment by kiswa** [comment]
Sorry I never responded to this.

You would change this line: https://github.com/kiswa/TaskBoard/blob/a835aa7bb83bfe0b7aa2136e864ca3ff76e60419/js/controllers/boardsItemForm.js#L81

to:

```javascript
$('#datepicker').datepicker({ dateFormat: 'dd/mm/yyyy' });
```

**Comment by brendantay** [comment]
Thank you @kiswa it was just deploying this tonight and this issue was bugging me!
However using yyyy gives me 20172017 (not sure if i am a special case - however dropping the last 2 yy resolved this)

Rather than me spending all night being even more confused than I was when I first began to try resolve this, can you let me know how to also change date format on the "Activity" sidebar - as it still shows MM/DD/YY

Thank you!

**Comment by kiswa** [comment]
@brendantay My bad on the `yy` vs `yyyy`!

I haven't tried it myself, but I think you can change this line: https://github.com/kiswa/TaskBoard/blob/master/partials/boardItemViewModal.html#L142

to:
```javascript
                <p class="detail">{{ activity.date | date:'dd/MM/yyyy' }}</p>
```

This one really is `yyyy` I double checked the docs.
