### ISSUE TITLE
Scrolling Issue

### ISSUE THREAD

**Issue by davidshenmue** [kiswa/TaskBoard#338]
Same as: https://github.com/kiswa/TaskBoard/issues/125

Issue is fixed in /js/controllers/board.js 

>    $scope.interval = $interval(checkDefaultBoard, 1250);

change variable to

>    $scope.interval = $interval(checkDefaultBoard, 11250);

I also added an extra value to this code as well

>    $scope.boardInterval = $interval($scope.loadBoards, 10000);

to 

>    $scope.boardInterval = $interval($scope.loadBoards, 60000);

You might need to refresh to see updates but the annoying scrolling to top bug is gone. I think the real problem is that loop is supposed to only run once before a board is loaded, but the loop never returns, and keeps running, not good at angular so can't fix it sorry.

Still not 100% fixed but it doesn't seem to jump up as often.

**Comment by kiswa** [comment]
It's actually intentional. The boards constantly update to make sure they have the latest changes from any other users. Unfortunately, it causes scrolling to reset every time.

This is getting fixed in the re-write (currently underway) so the boards will stay up-to-date and the scrolling will no longer be an issue.
