### ISSUE TITLE
Can't run branch re-write on apache with mysql

### ISSUE THREAD

**Issue by bbichero** [kiswa/TaskBoard#363]
Wanting to contribute,
I dedicated a VM, clone project and switch to re-write branch.
But impossible to run app ...
Browser display "TaskBoard is Loading..."

My apache virtual host:
```
<VirtualHost *:80>
	DocumentRoot /home/bbichero/TaskBoard/src
	ServerName task_board

	<Directory /home/bbichero/TaskBoard/src>
    		Options +FollowSymLinks
    		AllowOverride All
        	Options All
        	Require all granted
        </Directory>

	ErrorLog ${APACHE_LOG_DIR}/task_board.log

    	# Possible values include: debug, info, notice, warn, error,
    	# crit,
    	# alert, emerg.
    	LogLevel warn

</VirtualHost>
```
Console log:
![errors](https://image.noelshack.com/fichiers/2017/22/1496095532-screen-shot-2017-05-30-at-12-04-43-am.png)

I can't run test with mysql, I got errors:
![gulp-test-error](https://image.noelshack.com/fichiers/2017/22/1496095743-screen-shot-2017-05-30-at-12-08-42-am.png)

After changing `R::setup('sqlite:tests.db')` with the correct value, in for example: `TaskBoard/test/api/controllers/AttachmentsTest.php`, commands `gulp test` return exactly sames errors.

**Comment by kiswa** [comment]
I'm just going to ignore the test issues for now as they work fine in the original SQLite environment.

As for the site not loading: any browser errors, do you have `mod_rewrite` enabled? The `re-write` branch does some logging of its own too, so you could take a look at `dist/api/logs/api.log` (if I remember correctly) and see if there were any API errors.

**Comment by bbichero** [comment]
Yes all tests work with sqlite.
Yes I have mod_rewrite. I Was able to make auth form display it `src/index.html` was copying in /TaskBoard directory (root).
Why there is a `<base href="/dist/">` line in `index.html` if the file is in /dist ?
Are you sure that my apache virtualhost conf file is correct ?
Now I got a POST 500 error when loading page.
And the file `dist/api/logs/api.log` is not present, `dist/api/logs` neither.

**Comment by kiswa** [comment]
Oh, I forgot about the base href. If you've moved the `dist` directory contents to a directory served by Apache, then edit that to be `<base href="/">` and the rewrites should work accurately.

**Comment by bbichero** [comment]
Ok thanks, now that good, but impossible to work with mysql.
You can close this issue.

I can't find your email or a way to contact you so I will do here.
What is the point of re-write branch ? After make fun with taskBoard V1, it's better thant master branch V3.1, better I mean the design, the features. So if I contribute, the new code won't be on master branch ? Only in re-write ?

I really want to help TaskBoard community, but I want to understand the workflow.

**Comment by kiswa** [comment]
I actually prefer TaskBoard contact through GitHub, so here is good! ;)

I appreciate the offer for help, and I'll definitely need contributions in the future. The `re-write` branch is a *complete* re-write of TaskBoard to improve design of both the UI/UX and codebase. It includes unit tests and modern development tools to make development easier and safer. It is also planned to be a simple drop-in and run install process once it's done.

I generally don't accept PRs on `master`, and request they all go against the `dev` branch. Lately however, I haven't had any so it hasn't been an issue. I've been debating just freezing PRs until `re-write` is ready. The idea is that once it's ready, it will be merged to `master` and `dev`, and be the new code to work against.

So basically, the workflow is (normally) to checkout `dev`, make changes, then submit a PR. Once accepted I then merge `dev` to `master` and do other upkeep (version numbers, *etc.*). There's nothing wrong with continuing that, though it will likely lead to more work for me when it comes time to switch over to the `re-write` branch code.

Right now, I'm won't accept PRs against `re-write` as it's still a work in progress and not really ready for other devs. I wanted to develop it publicly, so users could see it and make suggestions. But that's all the contribution it needs for now.

Thank you for your help so far (I enjoyed not having to answer every recent issue because your answers were good). 

If you're interested, you can read through my blog and see what I've been doing on TaskBoard: https://matthewross.me/blog/

**Comment by bbichero** [comment]
Okay I understand ! As soon has I have time, I will work on `dev` :)
I'm happy that you apreciate my answers on recent issue, you can depend on me for all news issues.

At this time I work everyday on GitHub, so this isn't disturbing my day job.

I will check your blog !
Have a nice day.
