### ISSUE TITLE
Doubled scroll-bars

### ISSUE THREAD

**Issue by BlackEdder0815** [kiswa/TaskBoard#370]
If you have a big bunch of items, the scroll bars are doubled.
You have one scrollbar next to your column, which takes the items, and one scrollbar at the most right (for the whole page). One scrollbar should be enough ;-)

**Comment by kiswa** [comment]
Yeah, that should not be happening. What browser, OS, screen size?

**Comment by BlackEdder0815** [comment]
OS: Windows
Browser Firefox:
![grafik](https://user-images.githubusercontent.com/25084261/27637693-e98fab4e-5c10-11e7-977f-40f07235c51b.png)

Resolution: 
1920x1080 (fullscreen)

The behavior in Chrome is much better.

**Comment by kiswa** [comment]
From the screenshot, I'm guessing it's caused by whatever that blue-ish bar across the bottom is. I'll have to take a look at it in Windows with Firefox... probably a style issue somewhere.

**Comment by hbayindir** [comment]
This also happens in the Firefox 57 / Linux. I don't have the same blueish bar at the bottom in Linux.

Screenshot of the problem: ![taskbpard-firefox-problem](https://user-images.githubusercontent.com/479423/32980901-f2f30f2a-cc7f-11e7-8ca9-c48e8a4c3d14.png)

**Comment by olaulau** [comment]
it seems that the application works best with chrome on windows / linux. some bugs on macos, and too.

**Comment by hbayindir** [comment]
@olaulau Yes, it seems. However, it should be possible to equalize the user experience among browsers. With the latest user backlash Chrome created on login indication & sync, being browser agnostic more important than ever.

I personally don't use chrome anywhere if I'm not forced to, and only use it on sites which I'm absolutely have to. Otherwise, I use Firefox.
