### ISSUE TITLE
Long lists scroll back periodically.

### ISSUE THREAD

**Issue by hbayindir** [kiswa/TaskBoard#400]
The long lists in the boards automatically scroll back to the beginning every 10 seconds or so, this makes adding cards under big lists and reading long lists for issues very hard. Problem occurs both in Firefox and Chrome.

**Comment by lsmtom** [comment]
That is caused by ng-repeat of the board column during board data refresh. Add` track by lane.id` may solve the problem.

In partials/board.html, find
`<div class="boardColumn" data-ng-repeat="lane in currentBoard.ownLane | orderBy:'position':false"`
change it to
` <div class="boardColumn" data-ng-repeat="lane in currentBoard.ownLane | orderBy:'position':false track by lane.id"`

**Comment by hbayindir** [comment]
@lsmtom Thanks for the help. This seems like fixing the problem. Shall I create a pull request for the fix?

**Comment by therealmaxmoon** [comment]
The same issue exists if really long todo description exists. While scrolling in a long todo description, it jumps periodically back to the first line of the description.
