### ISSUE TITLE
User cannot access board

### ISSUE THREAD

**Issue by davidlag0** [kiswa/TaskBoard#503]
**Describe the bug**
A newly created user cannot access a newly created board even though he is provided access by the admin account. The issue is reproducible with the online demo.

**To Reproduce**
1. Log in with admin/admin credentials
2. Create a new user
3. Create a new board and provide access to the board to the newly created user.
4. Log out
5. Log with the user credentials
6. See the page that says no board is available

**Expected behavior**
I would expect the new user to be able to access the new board.

**Screenshots**
Steps above can be used to reproduce the issue at https://taskboard.matthewross.me/demo-live/

**Please complete the following information:**
- Doesn't seem to influence as the online demo has the issue.

**Additional context**
None.

**Comment by kiswa** [comment]
Screenshot actually would have been helpful, since after following your steps the new user can access the board.

Are you talking about the notice of "No Default Board" on the `boards` page? That is what it shows if the user doesn't have a default. You must then select a board to view from the dropdown at the top left.

If that's not what you meant, please provide more details and I'll re-open this issue.

**Comment by davidlag0** [comment]
Here are screenshots with the steps I took on the online demo to reproduce:

1. Log in with admin/admin credentials:

![image](https://user-images.githubusercontent.com/40720561/84540479-7208c900-acc3-11ea-8744-dd8e48a1f837.png)

![image](https://user-images.githubusercontent.com/40720561/84540529-8f3d9780-acc3-11ea-9777-060ed18b846b.png)

2. Create a new user:

![image](https://user-images.githubusercontent.com/40720561/84540626-d166d900-acc3-11ea-92ef-def1a5dbd0ce.png)

![image](https://user-images.githubusercontent.com/40720561/84540664-e479a900-acc3-11ea-877f-61beb94e3aa1.png)

3. Create new board and provide access to the board to the newly created user.

![image](https://user-images.githubusercontent.com/40720561/84552103-af7a5000-acdd-11ea-890a-7df35b1fbde7.png)

4. Log out

5. Log with the user credentials:

![image](https://user-images.githubusercontent.com/40720561/84552179-e5b7cf80-acdd-11ea-9ddb-1cb4b2705720.png)

6. Taken from last screenshot, specifically where it says the user does not have access to any board:

![image](https://user-images.githubusercontent.com/40720561/84552223-097b1580-acde-11ea-9696-b87826b53d38.png)

My screenshot taking app doesn't allow me to show it but the only choice in this drop-down menu is None:

![image](https://user-images.githubusercontent.com/40720561/84552274-29aad480-acde-11ea-9812-fad78e259f02.png)

If I'm using TaskBoard incorrectly, please let me know!

**Comment by kiswa** [comment]
Thank you for the screenshots! Because of the "Add User" screenshot, I was able to determine that the problem happens when the user is created without a selected Security Level. Although it looks like it defaults to User, what is actually stored is an invalid level, so the board assignments don't show up.

That was a strange one to find, and I'll get a fix for it soon.

**Comment by davidlag0** [comment]
My pleasure! Thanks again for your help. I've been using GitHub for a while but never to report issues and work with other devs to get them resolved so I'm learning through the process! With your response, I know we have a workaround now so we can move forward and start using TaskBoard and upgrade once the fix is out! :)
