### ISSUE TITLE
Touchpad controls

### ISSUE THREAD

**Issue by CConnection** [kiswa/TaskBoard#74]
I like your interface very much. Clean and simple. Just tried it out on my ipad as it is one of my working horses. I can't move the items, so I think there aren't any touch controls implemented yet?

**Comment by goldingo** [comment]
I have no time to move this task forward but I would consider paying to have it made. Native is great idea but let's do it mobile friendly first. so user feel the need to have the IOS after. So user can move tasks and make comments with an tablet or smartphone. If you feel like up to it provide me a quote and I see what I can do. To use it on a professional level I need the email notification as well. I am trying to convince my buddy to work on that part. This is a great app you did here. Congrats.

**Comment by kiswa** [comment]
Wow, thank you! I cannot quote out work on TaskBoard, because I can't guarantee my time will be available to get the work done, and I don't want to leave anyone feeling slighted. My day job is also development, and I don't always have the desire to keep coding when I get home.

That said, I do really appreciate those who have made contributions; both via pull requests and a few monetary contributions at http://taskboard.matthewross.me/

Version 0.3.0 should be done relatively soon, and this is up for the next release after that. I'll also be going through existing issues and re-prioritizing, so I'll probably move email up as well. You are correct in saying those features would help bring TaskBoard to a more 'professional level' of usability.
